services:
  web:
    image: shinsenter/symfony:php8.4
    volumes:
      - ./symfony:/var/www/html
    ports:
      - "8080:80"
    networks:
      - app_network                    # ← AJOUTÉ
    environment:
      MERCURE_URL: http://mercure/.well-known/mercure
      MERCURE_PUBLIC_URL: http://localhost:9090/.well-known/mercure
      MERCURE_JWT_SECRET: your_super_secret_jwt_key_min_32_chars!!

  redis:
    image: redis:8.6.3-trixie
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app_network                    # ← AJOUTÉ

  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    ports:
      - "9090:80"
    environment:
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: 'your_super_secret_jwt_key_min_32_chars!!'
      MERCURE_SUBSCRIBER_JWT_KEY: 'your_super_secret_jwt_key_min_32_chars!!'
      MERCURE_EXTRA_DIRECTIVES: |
        anonymous
        cors_origins http://localhost:8080 http://localhost:3000
    command: /usr/bin/caddy run --config /etc/caddy/Caddyfile --adapter caddyfile
    networks:
      - app_network

networks:
  app_network:
    driver: bridge