<?php

namespace ContainerQgaE3z7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServicesResetterService extends App_KernelProdContainer
{
    /*
     * Gets the public 'services_resetter' shared service.
     *
     * @return \Symfony\Component\HttpKernel\DependencyInjection\ServicesResetter
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['services_resetter'] = new \Symfony\Component\HttpKernel\DependencyInjection\ServicesResetter(new RewindableGenerator(function () use ($container) {
            if (isset($container->privates['controller.cache_attribute_listener'])) {
                yield 'controller.cache_attribute_listener' => ($container->privates['controller.cache_attribute_listener'] ?? null);
            }
            if (isset($container->services['request_stack'])) {
                yield 'request_stack' => ($container->services['request_stack'] ?? null);
            }
            if (isset($container->privates['container.env_var_processor'])) {
                yield 'container.env_var_processor' => ($container->privates['container.env_var_processor'] ?? null);
            }
            if (isset($container->services['cache.app'])) {
                yield 'cache.app' => ($container->services['cache.app'] ?? null);
            }
            if (isset($container->services['cache.system'])) {
                yield 'cache.system' => ($container->services['cache.system'] ?? null);
            }
            if (false) {
                yield 'cache.validator' => null;
            }
            if (false) {
                yield 'cache.serializer' => null;
            }
            if (false) {
                yield 'cache.property_info' => null;
            }
            if (isset($container->services['cache.http_client.pool'])) {
                yield 'cache.http_client.pool' => ($container->services['cache.http_client.pool'] ?? null);
            }
            if (isset($container->privates['http_client.transport'])) {
                yield 'http_client.transport' => ($container->privates['http_client.transport'] ?? null);
            }
            if (isset($container->privates['http_client.uri_template'])) {
                yield 'http_client' => ($container->privates['http_client.uri_template'] ?? null);
            }
            if (isset($container->services['cache.rate_limiter'])) {
                yield 'cache.rate_limiter' => ($container->services['cache.rate_limiter'] ?? null);
            }
            if (isset($container->privates['session_listener'])) {
                yield 'session_listener' => ($container->privates['session_listener'] ?? null);
            }
            if (isset($container->privates['twig'])) {
                yield 'twig' => ($container->privates['twig'] ?? null);
            }
        }, fn () => 0 + (int) (isset($container->privates['controller.cache_attribute_listener'])) + (int) (isset($container->services['request_stack'])) + (int) (isset($container->privates['container.env_var_processor'])) + (int) (isset($container->services['cache.app'])) + (int) (isset($container->services['cache.system'])) + (int) (false) + (int) (false) + (int) (false) + (int) (isset($container->services['cache.http_client.pool'])) + (int) (isset($container->privates['http_client.transport'])) + (int) (isset($container->privates['http_client.uri_template'])) + (int) (isset($container->services['cache.rate_limiter'])) + (int) (isset($container->privates['session_listener'])) + (int) (isset($container->privates['twig']))), ['controller.cache_attribute_listener' => ['?reset'], 'request_stack' => ['?resetRequestFormats'], 'container.env_var_processor' => ['reset'], 'cache.app' => ['reset'], 'cache.system' => ['reset'], 'cache.validator' => ['reset'], 'cache.serializer' => ['reset'], 'cache.property_info' => ['reset'], 'cache.http_client.pool' => ['reset'], 'http_client.transport' => ['?reset'], 'http_client' => ['?reset'], 'cache.rate_limiter' => ['reset'], 'session_listener' => ['reset'], 'twig' => ['?resetGlobals']]);
    }
}
