<?php

namespace ContainerEf4KRdp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_CacheConnection_YNOeIpService extends App_KernelProdContainer
{
    /*
     * Gets the private '.cache_connection.yN_OeIp' shared service.
     *
     * @return \Symfony\Component\Cache\Adapter\AbstractAdapter
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.cache_connection.yN_OeIp'] = \Symfony\Component\Cache\Adapter\AbstractAdapter::createConnection($container->getEnv('REDIS_URL'), ['lazy' => true]);
    }
}
