<?php

namespace ContainerEf4KRdp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHomeControllerroomService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator..mf_ReP.App\Controller\HomeController::room()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..mf_ReP.App\\Controller\\HomeController::room()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'redisManager' => ['privates', 'App\\Service\\RedisDataManager', 'getRedisDataManagerService', true],
            'csrfTokenManager' => ['privates', 'security.csrf.token_manager', 'getSecurity_Csrf_TokenManagerService', true],
            'autosaveLimiter' => ['privates', 'limiter.autosave_limiter', 'getLimiter_AutosaveLimiterService', true],
            'hub' => ['privates', 'mercure.hub.default', 'getMercure_Hub_DefaultService', true],
        ], [
            'redisManager' => 'App\\Service\\RedisDataManager',
            'csrfTokenManager' => '?',
            'autosaveLimiter' => 'Symfony\\Component\\RateLimiter\\RateLimiterFactory',
            'hub' => '?',
        ]))->withContext('App\\Controller\\HomeController::room()', $container);
    }
}
