<?php

namespace Container9dU4cuB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getErrorControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iWu32xY.App\Controller\ErrorController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iWu32xY.App\\Controller\\ErrorController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'exception' => ['privates', '.errored..service_locator.iWu32xY.Throwable', NULL, 'Cannot autowire service ".service_locator.iWu32xY": it references interface "Throwable" but no such service exists. Did you create an instantiable class that implements this interface?'],
        ], [
            'exception' => 'Throwable',
        ]))->withContext('App\\Controller\\ErrorController::show()', $container);
    }
}
