<?php

namespace Container9dU4cuB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRateLimiterFactoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.qAPHk.e.Symfony\Component\RateLimiter\RateLimiterFactory' shared service.
     *
     * @return \Symfony\Component\RateLimiter\RateLimiterFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.qAPHk.e": it references class "Symfony\\Component\\RateLimiter\\RateLimiterFactory" but no such service exists. You should maybe alias this class to the existing "limiter.autosave_limiter" service.');
    }
}
