<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9dU4cuB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9dU4cuB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9dU4cuB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9dU4cuB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9dU4cuB\App_KernelDevDebugContainer([
    'container.build_hash' => '9dU4cuB',
    'container.build_id' => 'ddcc1427',
    'container.build_time' => 1780048780,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container9dU4cuB');
