<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_room_update' => [['token'], ['_controller' => 'App\\Controller\\AutoSaveController::updateRoom'], [], [['text', '/update'], ['variable', '/', '[^/]++', 'token', true]], [], [], []],
    'app_room' => [['token'], ['_controller' => 'App\\Controller\\HomeController::room'], [], [['variable', '/', '[^/]++', 'token', true]], [], [], []],
    'app_home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
    'App\Controller\AutoSaveController::updateRoom' => [['token'], ['_controller' => 'App\\Controller\\AutoSaveController::updateRoom'], [], [['text', '/update'], ['variable', '/', '[^/]++', 'token', true]], [], [], []],
    'App\Controller\HomeController::room' => [['token'], ['_controller' => 'App\\Controller\\HomeController::room'], [], [['variable', '/', '[^/]++', 'token', true]], [], [], []],
    'App\Controller\HomeController::index' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
];
