<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSxOJrG2\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSxOJrG2/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerSxOJrG2.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerSxOJrG2\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerSxOJrG2\App_KernelProdContainer([
    'container.build_hash' => 'SxOJrG2',
    'container.build_id' => '25221782',
    'container.build_time' => 1780065462,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSxOJrG2');
