<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQgaE3z7\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQgaE3z7/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerQgaE3z7.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerQgaE3z7\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerQgaE3z7\App_KernelProdContainer([
    'container.build_hash' => 'QgaE3z7',
    'container.build_id' => '95095a20',
    'container.build_time' => 1780070493,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQgaE3z7');
