<?php

namespace ContainerXbuysud;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAutoSaveControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\AutoSaveController' shared autowired service.
     *
     * @return \App\Controller\AutoSaveController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/AutoSaveController.php';

        $container->services['App\\Controller\\AutoSaveController'] = $instance = new \App\Controller\AutoSaveController();

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\AutoSaveController', $container));

        return $instance;
    }
}
