<?php

namespace ContainerXbuysud;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMercure_Hub_DefaultService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'mercure.hub.default' shared service.
     *
     * @return \Symfony\Component\Mercure\Hub
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/mercure/src/HubInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/mercure/src/RemoteHubInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/mercure/src/Hub.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/mercure/src/Jwt/TokenProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/mercure/src/Jwt/FactoryTokenProvider.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/mercure/src/Jwt/TokenFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/mercure/src/Jwt/LcobucciFactory.php';

        $a = new class(fn () => new \Symfony\Component\Mercure\Jwt\LcobucciFactory($container->getEnv('MERCURE_JWT_SECRET'), 'hmac.sha256', NULL, '')) extends \Symfony\Component\DependencyInjection\Argument\LazyClosure implements \Symfony\Component\Mercure\Jwt\TokenFactoryInterface { public function create(?array $subscribe = [], ?array $publish = [], array $additionalClaims = []): string { return $this->service->create(...\func_get_args()); } };

        return $container->privates['mercure.hub.default'] = new \Symfony\Component\Mercure\Hub($container->getEnv('default::MERCURE_URL'), new \Symfony\Component\Mercure\Jwt\FactoryTokenProvider($a, [], ['*']), $a, $container->getEnv('default::MERCURE_PUBLIC_URL'), ($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')));
    }
}
