<?php

namespace ContainerSN0wFAa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_1pK4BXAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.1pK4BXA' shared service.
     *
     * @return \App\Controller\RedisDataManager
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\AutoSaveController::updateRoom()": the $redisManager argument is type-hinted with the non-existent class or interface: "App\\Controller\\RedisDataManager". Did you forget to add a use statement?');
    }
}
