<?php

namespace ContainerSN0wFAa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAutoSaveControllerupdateRoomService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qAPHk.e.App\Controller\AutoSaveController::updateRoom()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qAPHk.e.App\\Controller\\AutoSaveController::updateRoom()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'redisManager' => ['privates', '.errored.1pK4BXA', NULL, 'Cannot determine controller argument for "App\\Controller\\AutoSaveController::updateRoom()": the $redisManager argument is type-hinted with the non-existent class or interface: "App\\Controller\\RedisDataManager". Did you forget to add a use statement?'],
            'autosaveLimiter' => ['privates', '.errored..service_locator.qAPHk.e.Symfony\\Component\\RateLimiter\\RateLimiterFactory', NULL, 'Cannot autowire service ".service_locator.qAPHk.e": it references class "Symfony\\Component\\RateLimiter\\RateLimiterFactory" but no such service exists. You should maybe alias this class to the existing "limiter.autosave_limiter" service.'],
            'csrfTokenManager' => ['privates', 'security.csrf.token_manager', 'getSecurity_Csrf_TokenManagerService', true],
        ], [
            'redisManager' => '?',
            'autosaveLimiter' => 'Symfony\\Component\\RateLimiter\\RateLimiterFactory',
            'csrfTokenManager' => '?',
        ]))->withContext('App\\Controller\\AutoSaveController::updateRoom()', $container);
    }
}
