<?php

namespace ContainerSN0wFAa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRedisDataManagerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\RedisDataManager' shared autowired service.
     *
     * @return \App\Service\RedisDataManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/RedisDataManager.php';

        return $container->privates['App\\Service\\RedisDataManager'] = new \App\Service\RedisDataManager(($container->services['cache.app'] ?? $container->load('getCache_AppService')));
    }
}
