<?php

namespace ContainerSxOJrG2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLimiter_AutosaveLimiterService extends App_KernelProdContainer
{
    /*
     * Gets the private 'limiter.autosave_limiter' shared service.
     *
     * @return \Symfony\Component\RateLimiter\RateLimiterFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['limiter.autosave_limiter'] = new \Symfony\Component\RateLimiter\RateLimiterFactory(['policy' => 'token_bucket', 'limit' => 15, 'rate' => ['amount' => 5, 'interval' => '1 minute'], 'id' => 'autosave_limiter'], new \Symfony\Component\RateLimiter\Storage\CacheStorage(($container->services['cache.rate_limiter'] ?? $container->load('getCache_RateLimiterService'))), NULL);
    }
}
